import { describe, expect, it } from 'vitest';
import { Application, Profile, generateApprovals, scoreRisk, startReady, validateDocument } from './core.js';
const profile:Profile={businessName:'GreenForge Manufacturing Pvt. Ltd.',industry:'Manufacturing',businessType:'Private Limited',location:'Pune',landType:'Notified industrial estate',investment:8.5,employees:85,environmentalImpact:'low'};
function draft():Application{return {id:'TEST',ownerId:'TEST',profile,status:'DRAFT',createdAt:new Date().toISOString(),approvals:generateApprovals(profile),documents:[],risk:{score:0,level:'LOW',factors:[],provisionalEligible:false},events:[],notifications:[]}}
describe('approval engine',()=>{
  it('generates a tailored checklist with prerequisite links',()=>{const a=draft();expect(a.approvals.length).toBeGreaterThanOrEqual(10);expect(a.approvals.find(x=>x.key==='fire')?.dependsOn).toContain('factory-plan');expect(generateApprovals({...profile,industry:'Food Processing'}).some(x=>x.key==='food')).toBe(true)});
  it('starts independent approvals together and releases dependent ones later',()=>{const a=draft();const started=startReady(a);expect(started.length).toBeGreaterThan(5);expect(a.approvals.find(x=>x.key==='fire')?.status).toBe('WAITING');a.approvals.find(x=>x.key==='factory-plan')!.status='APPROVED';expect(startReady(a)).toContain('Fire NOC')});
});
describe('document checks and risk',()=>{
  it('flags name mismatch and missing fire exits',()=>{const v=validateDocument('Factory Layout Plan','factory-layout-plan.txt','text/plain','Factory Layout Plan\nBusiness: Different Industries LLP\nProduction area marked.',profile);expect(v.result).toBe('ACTION_REQUIRED');expect(v.reasons).toContain('Business name consistent');expect(v.reasons).toContain('Fire exits indicated')});
  it('marks valid text document verified and opaque PDF for officer review',()=>{expect(validateDocument('Factory Layout Plan','factory-layout-plan.txt','text/plain',`Factory Layout Plan\nBusiness: ${profile.businessName}\nfire exit`,profile).result).toBe('VERIFIED');expect(validateDocument('PAN Card','pan-card.pdf','application/pdf','',profile).result).toBe('MANUAL_REVIEW')});
  it('explains each score and lowers risk as documents become complete',()=>{const a=draft();const first=scoreRisk(a);for(const type of [...new Set(a.approvals.flatMap(x=>x.docs))])a.documents.push({id:type,type,name:`${type}.txt`,mime:'text/plain',size:10,uploadedAt:new Date().toISOString(),validation:{classification:type,confidence:94,checks:[],result:'VERIFIED',reasons:[],method:'Rule-based text checks'}});const second=scoreRisk(a);expect(second.score).toBeLessThan(first.score);expect(second.level).toBe('LOW');expect(second.provisionalEligible).toBe(true);expect(second.factors.reduce((n,x)=>n+x.points,0)).toBe(second.score)});
});
