import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { z, ZodError } from 'zod';
import { Application, Role, Store, emit, generateApprovals, requiredDocTypes, scoreRisk, startReady, updateOverall, validateDocument } from './core.js';
import { dataFile, storageRoot, demoUsers, makeSeed, passwordHash } from './seed.js';
import { validateWithFallback } from './aiClient.js';

const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
const secret=process.env.JWT_SECRET||'udyog-setu-local-demo-only-change-for-deployment';
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(_req,file,cb)=>cb(null,['application/pdf','image/png','image/jpeg','text/plain'].includes(file.mimetype))});
type AuthReq=Request & { user?:{id:string;role:Role} };
function db():Store {if(!existsSync(dataFile)){mkdirSync(dirname(dataFile),{recursive:true});writeFileSync(dataFile,JSON.stringify(makeSeed(),null,2));}return JSON.parse(readFileSync(dataFile,'utf8')) as Store;}
function save(store:Store){mkdirSync(dirname(dataFile),{recursive:true});writeFileSync(dataFile,JSON.stringify(store,null,2));}
function fail(res:Response,status:number,message:string){return res.status(status).json({error:message});}
function auth(req:AuthReq,res:Response,next:NextFunction){const token=req.headers.authorization?.replace(/^Bearer /,'');try{if(!token)return fail(res,401,'Please enter the demo to continue.');req.user=jwt.verify(token,secret) as {id:string;role:Role};next();}catch{return fail(res,401,'Your demo session expired. Please enter again.');}}
function role(...roles:Role[]){return (req:AuthReq,res:Response,next:NextFunction)=>roles.includes(req.user!.role)?next():fail(res,403,'This action is not available for your demo role.');}
function getApp(req:AuthReq,res:Response,store:Store):Application|undefined{const target=store.applications.find(a=>a.id===req.params.id);if(!target){fail(res,404,'Application not found.');return;}if(req.user!.role==='ENTREPRENEUR'&&target.ownerId!==req.user!.id){fail(res,403,'You can only view your own application.');return;}return target;}
const profileSchema=z.object({businessName:z.string().min(3),industry:z.enum(['Manufacturing','Food Processing','Chemicals','Textiles','Electronics','Logistics']),businessType:z.string().min(2),location:z.string().min(2),landType:z.string().min(2),investment:z.coerce.number().positive().max(10000),employees:z.coerce.number().int().positive().max(100000),environmentalImpact:z.enum(['low','medium','high'])});
const asyncHandler=(fn:(req:AuthReq,res:Response)=>unknown)=>(req:AuthReq,res:Response,next:NextFunction)=>Promise.resolve(fn(req,res)).catch(next);

app.get('/api/health',(_req,res)=>res.json({ok:true,mode:'Prototype / Sandbox'}));
app.post('/api/auth/login',(req,res)=>{
  const {email,password}=req.body||{};const user=demoUsers.find(u=>u.email===email);
  if(!user||!bcrypt.compareSync(String(password||''),passwordHash))return fail(res,401,'Demo credentials are incorrect.');
  const token=jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'12h'});return res.json({token,user});
});
app.post('/api/auth/demo',(req,res)=>{
  const selected=String(req.body?.role||'ENTREPRENEUR').toUpperCase();const user=demoUsers.find(u=>u.role===selected);
  if(!user)return fail(res,400,'Choose Entrepreneur, Officer, or Admin.');
  return res.json({token:jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'12h'}),user});
});
app.get('/api/auth/me',auth,(req:AuthReq,res)=>res.json({user:demoUsers.find(u=>u.id===req.user!.id)}));
app.get('/api/applications',auth,(req:AuthReq,res)=>{const store=db();res.json(store.applications.filter(a=>req.user!.role!=='ENTREPRENEUR'||a.ownerId===req.user!.id).map(a=>({id:a.id,profile:a.profile,status:a.status,createdAt:a.createdAt,risk:a.risk,summary:{total:a.approvals.length,approved:a.approvals.filter(x=>x.status==='APPROVED').length,inReview:a.approvals.filter(x=>x.status==='IN_REVIEW').length}})));});
app.post('/api/applications',auth,role('ENTREPRENEUR'),(req:AuthReq,res)=>{const profile=profileSchema.parse(req.body);const store=db();const id=`US-MH-2026-${String(124+store.applications.length).padStart(5,'0')}`;const target:Application={id,ownerId:req.user!.id,profile,status:'DRAFT',createdAt:new Date().toISOString(),approvals:generateApprovals(profile,id),documents:[],risk:{score:0,level:'LOW',factors:[],provisionalEligible:false},events:[],notifications:[]};target.risk=scoreRisk(target);emit(target,'APPLICATION_CREATED','Entrepreneur','Business profile saved and approval map generated');store.applications.unshift(target);save(store);res.status(201).json(target);});
app.get('/api/applications/:id',auth,(req:AuthReq,res)=>{const a=getApp(req,res,db());if(a)res.json(a);});
app.post('/api/applications/:id/analyze',auth,role('ENTREPRENEUR'),(req:AuthReq,res)=>{const store=db(),a=getApp(req,res,store);if(!a)return;if(a.status!=='DRAFT')return fail(res,409,'Submitted applications cannot be re-analyzed.');a.profile=profileSchema.parse(req.body);a.approvals=generateApprovals(a.profile,a.id);a.risk=scoreRisk(a);emit(a,'APPLICATION_ANALYZED','Approval engine',`${a.approvals.length} possible approvals mapped from business profile`);save(store);res.json(a);});
app.get('/api/applications/:id/approvals',auth,(req:AuthReq,res)=>{const a=getApp(req,res,db());if(a)res.json(a.approvals);});
app.get('/api/applications/:id/risk',auth,(req:AuthReq,res)=>{const a=getApp(req,res,db());if(a)res.json(a.risk);});
app.get('/api/applications/:id/timeline',auth,(req:AuthReq,res)=>{const a=getApp(req,res,db());if(a)res.json(a.events);});
app.get('/api/applications/:id/notifications',auth,(req:AuthReq,res)=>{const a=getApp(req,res,db());if(a)res.json(a.notifications);});
app.post('/api/applications/:id/notifications/:notificationId/read',auth,(req:AuthReq,res)=>{const store=db(),a=getApp(req,res,store);if(!a)return;const n=a.notifications.find(x=>x.id===req.params.notificationId);if(!n)return fail(res,404,'Notification not found.');n.read=true;save(store);res.json(n);});
app.post('/api/applications/:id/submit',auth,role('ENTREPRENEUR'),(req:AuthReq,res)=>{const store=db(),a=getApp(req,res,store);if(!a)return;if(a.status!=='DRAFT')return fail(res,409,'Application has already been submitted.');const missing=requiredDocTypes(a).filter(t=>!a.documents.some(d=>d.type===t&&['VERIFIED','MANUAL_REVIEW'].includes(d.validation.result)));if(missing.length)return fail(res,422,`Correct or upload these documents before submission: ${missing.join(', ')}.`);a.risk=scoreRisk(a);emit(a,'APPROVAL_SUBMITTED','Entrepreneur','Unified application submitted');const started=startReady(a);a.status='IN_PROGRESS';emit(a,'APPROVAL_STARTED','Workflow engine',`${started.length} independent approvals started in parallel`);save(store);res.json({application:a,started});});
app.post('/api/documents/upload',auth,role('ENTREPRENEUR'),upload.single('file'),asyncHandler(async(req:AuthReq,res)=>{const store=db();const a=store.applications.find(x=>x.id===req.body.applicationId&&x.ownerId===req.user!.id);if(!a)return fail(res,404,'Application not found.');if(!req.file)return fail(res,400,'Select a PDF, PNG, JPEG, or text file up to 8 MB.');const type=String(req.body.type||'');if(!requiredDocTypes(a).includes(type))return fail(res,400,'Select a document type from the required list.');const content=req.file.mimetype==='text/plain'?req.file.buffer.toString('utf8').slice(0,100000):'';const validation=await validateWithFallback(type,req.file.originalname,req.file.mimetype,content,a.profile);const id=`DOC-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const directory=resolve(storageRoot,'uploads');mkdirSync(directory,{recursive:true});writeFileSync(resolve(directory,id),req.file.buffer);a.documents=a.documents.filter(d=>d.type!==type);a.documents.push({id,type,name:req.file.originalname,mime:req.file.mimetype,size:req.file.size,uploadedAt:new Date().toISOString(),validation});a.notifications=a.notifications.filter(n=>!n.message.startsWith(`${type} needs correction`)&&!n.message.startsWith(`${type}: action required`));a.risk=scoreRisk(a);emit(a,'DOCUMENT_UPLOADED','Entrepreneur',`${type} uploaded`);emit(a,'DOCUMENT_VALIDATED','Rule-based validation',`${type}: ${validation.result.replace('_',' ').toLowerCase()}`);save(store);res.status(201).json({document:a.documents.at(-1),risk:a.risk});}));
app.post('/api/documents/:id/validate',auth,(req:AuthReq,res)=>{const store=db();const a=store.applications.find(x=>x.documents.some(d=>d.id===req.params.id)&& (req.user!.role!=='ENTREPRENEUR'||x.ownerId===req.user!.id));if(!a)return fail(res,404,'Document not found.');const doc=a.documents.find(d=>d.id===req.params.id)!;if(doc.mime!=='text/plain')return res.json(doc.validation);const filepath=resolve(storageRoot,'uploads',doc.id);if(existsSync(filepath))doc.validation=validateDocument(doc.type,doc.name,doc.mime,readFileSync(filepath,'utf8'),a.profile);a.risk=scoreRisk(a);save(store);res.json(doc.validation);});
app.get('/api/documents/:id/file',auth,(req:AuthReq,res)=>{const store=db();const a=store.applications.find(x=>x.documents.some(d=>d.id===req.params.id)&&(req.user!.role!=='ENTREPRENEUR'||x.ownerId===req.user!.id));if(!a)return fail(res,404,'Document not found.');const doc=a.documents.find(d=>d.id===req.params.id)!;const filepath=resolve(storageRoot,'uploads',doc.id);if(!existsSync(filepath))return fail(res,404,'File is unavailable in this demo dataset.');res.setHeader('Content-Type',doc.mime);res.setHeader('Content-Disposition',`inline; filename="${doc.name.replace(/["\r\n]/g,'')}"`);res.sendFile(filepath);});
app.get('/api/officer/applications',auth,role('OFFICER','ADMIN'),(_req,res)=>res.json(db().applications.filter(a=>a.status!=='DRAFT')));
function decision(action:'approve'|'reject'|'request-documents'){
  return (req:AuthReq,res:Response)=>{const store=db();const a=store.applications.find(x=>x.approvals.some(p=>p.id===req.params.id));if(!a)return fail(res,404,'Approval request not found.');const approval=a.approvals.find(p=>p.id===req.params.id)!;if(!['IN_REVIEW','ACTION_REQUIRED'].includes(approval.status))return fail(res,409,'This approval is not ready for a decision.');const reason=String(req.body?.reason||'').trim();if(action!=='approve'&&reason.length<5)return fail(res,400,'Please enter a clear reason of at least five characters.');approval.status=action==='approve'?'APPROVED':action==='reject'?'REJECTED':'ACTION_REQUIRED';approval.reason=reason||undefined;approval.decidedAt=new Date().toISOString();const event=action==='approve'?'APPROVAL_APPROVED':action==='reject'?'APPROVAL_REJECTED':'DOCUMENT_REQUESTED';emit(a,event,'Department officer',`${approval.name}: ${action==='approve'?'approved':action==='reject'?'rejected':'additional document requested'}${reason?` — ${reason}`:''}`,approval.department);if(action==='approve'){const started=startReady(a);if(started.length)emit(a,'APPROVAL_STARTED','Workflow engine',`${started.length} dependent approval${started.length>1?'s':''} now started`);}updateOverall(a);save(store);res.json({application:a,approval});};
}
app.post('/api/approvals/:id/approve',auth,role('OFFICER'),decision('approve'));
app.post('/api/approvals/:id/reject',auth,role('OFFICER'),decision('reject'));
app.post('/api/approvals/:id/request-documents',auth,role('OFFICER'),decision('request-documents'));
app.get('/api/analytics',auth,role('ADMIN'),(_req,res)=>{const all=db().applications;const approvals=all.flatMap(a=>a.approvals);const departments=[...new Set(approvals.map(a=>a.department))].map(name=>({name,total:approvals.filter(a=>a.department===name).length,pending:approvals.filter(a=>a.department===name&&a.status==='IN_REVIEW').length}));res.json({applications:all.length,documents:all.reduce((n,a)=>n+a.documents.length,0),approvals:approvals.length,distribution:Object.entries(approvals.reduce<Record<string,number>>((m,a)=>(m[a.status]=(m[a.status]||0)+1,m),{})).map(([name,value])=>({name,value})),risk:['LOW','MEDIUM','HIGH'].map(name=>({name,value:all.filter(a=>a.risk.level===name).length})),departments,simulation:{traditionalDays:36,parallelDays:18,assumption:'Prototype simulation based on configured workflow assumptions'}});});
app.get('/api/schemes',auth,(_req,res)=>res.json([{name:'MSME support discovery',fit:'Manufacturing and food processing enterprises',support:'Capital assistance may be available',source:'Demo data — verify eligibility through official government sources.'},{name:'Energy efficiency support',fit:'Units planning efficiency upgrades',support:'Potential advisory and financial support',source:'Demo data — verify eligibility through official government sources.'},{name:'Export readiness support',fit:'Manufacturing exporters',support:'Potential market access support',source:'Demo data — verify eligibility through official government sources.'}]));
app.get('/api/integrations',auth,(_req,res)=>res.json(['DigiLocker','GSTN','PAN verification','e-District','Aadhaar e-KYC','Department systems'].map(name=>({name,status:'Prototype / Sandbox',connected:false}))));
app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(err instanceof ZodError)return fail(res,400,err.issues.map(x=>`${x.path.join('.')}: ${x.message}`).join('; '));if(err instanceof multer.MulterError)return fail(res,400,err.code==='LIMIT_FILE_SIZE'?'File exceeds the 8 MB limit.':'Unable to upload this file.');console.error(err);return fail(res,500,'This action could not be completed. Please try again.');});
const port=Number(process.env.PORT||4000);app.listen(port,()=>console.log(`Udyog Setu API on http://localhost:${port}`));
